### ISSUE TITLE
_'milnet' is not defined_ in  _train_tcga.py_

### ISSUE THREAD

**Issue by jingweitan** [HHHedo/IBMIL#1]
Hi, I am trying to implement your code. But, I found that in the _train_tcga.py_ , there is an error occured  _'milnet' is not defined_ . May I know where can I get the milnet model?  Thanks in advance.

**Comment by HHHedo** [comment]
> Hi, I am trying to implement your code. But, I found that in the _train_tcga.py_ , there is an error occured _'milnet' is not defined_ . May I know where can I get the milnet model? Thanks in advance.

We have fixed it. Please refer to:
https://github.com/HHHedo/IBMIL/blob/f7c776c7cf194d2e74961c425cac625096699513/train_tcga.py#L281-L289

**Comment by jingweitan** [comment]
Thanks a lot!
