### ISSUE TITLE
val is test?

### ISSUE THREAD

**Issue by lingxitong** [HHHedo/IBMIL#10]
in your train file,I see you train one epoch and then test one and save the best model?Can I understand your val is test? other MIL paper always select the best in val and test,can you explain it?
<img width="718" alt="微信图片_20240104011726" src="https://github.com/HHHedo/IBMIL/assets/72933417/9774a58c-5de7-4f37-83f8-b48809b289f5">

**Comment by HHHedo** [comment]
Hi, We report the results of last epoch, as reporting the best model is a kind of data leakage.As mentioned in our paper, the codebase is mainly based on dsmil. So we just copied that training one epoch and then test one.在 2024年1月4日，01:18，Toby ***@***.***> 写道：﻿
in your train file,I see you train one epoch and then test one and save the best model?Can I understand your val is test? other MIL paper always select the best in val and test,can you explain it?
_20240104011726.png (view on web)

**Comment by lingxitong** [comment]
ok，thanks，report the last is right
