### ISSUE TITLE
Data organization of train_tcga.py

### ISSUE THREAD

**Issue by pxliang** [HHHedo/IBMIL#12]
Could you please provide the data organization of the train_tcga.py? Can you also provide data.csv file example for reference?

**Comment by HHHedo** [comment]
We generated the csv follows [dsmil](https://github.com/binli123/dsmil-wsi/blob/master/compute_feats.py), which has been updated as requested ([here](https://github.com/HHHedo/IBMIL/tree/main/datasets_csv)).
To alleviate the impact of data split for evaluation, we recommend cross-validation as some papers do.
