### ISSUE TITLE
TCGA Dataset Training and Testing Distributions

### ISSUE THREAD

**Issue by bryanwong17** [HHHedo/IBMIL#16]
Hi, could you please share with me the distribution of slides used for training and testing in the TCGA dataset, along with their respective labels? From my understanding, the patches were obtained from the DSMIL authors. Is it correct that you followed their approach to create the distributions?

I noticed that it's mentioned there are a total of 836 training slides and 210 testing slides. However, upon examining the `TEST_ID.csv` file from [this link](https://drive.google.com/drive/folders/1UobMSqJEqINX2izxrwbgprugjlTporSQ), I observed that there are 214 testing slides. Could you provide clarification on this? And also which slides are used for training? Thank you!

**Comment by HHHedo** [comment]
I create the training and test slides follow the dsmil's [code](https://github.com/binli123/dsmil-wsi/blob/master/compute_feats.py), and the results are [here](https://github.com/HHHedo/IBMIL/blob/main/datasets_csv/TCGA.csv).

**Comment by bryanwong17** [comment]
Thank you for your reply. But the results [here](https://github.com/HHHedo/IBMIL/blob/main/datasets_csv/TCGA.csv) contains all training and testing slides. Could you let me know which slides are used for training/testing?

**Comment by HHHedo** [comment]
Please refer to the [code](https://github.com/HHHedo/IBMIL/blob/61ac749933bba3418238f2ab09af866dd276c695/train_tcga.py#L300-L311).

**Comment by bryanwong17** [comment]
Thank you!

**Comment by bryanwong17** [comment]
Just wanted to double-check: Does the label 0 represent LUAD, and 1 represent LUSC in [this](https://github.com/HHHedo/IBMIL/blob/main/datasets_csv/TCGA.csv)?
