### ISSUE TITLE
Features used in the experiments presented in the paper

### ISSUE THREAD

**Issue by ritamartinspereira** [HHHedo/IBMIL#18]
Hi, I really liked your paper! 
I was trying to simulate those results you got for the Camelyon16 dataset, but i used the pre-computed features available on the Github of DSMIL and didn't get close results to those that you have.
In your experiments, did you use the pre-computed features or did you do the pre-processing of the images and then extract the features? 
Thank you

**Comment by HHHedo** [comment]
Sorry for the delayed response.
The tcga patches are processed by dsmil, and we pre-processe the WSIs ourselves and achieve around 7200 patches per WSI.
This is the [Baidu cloud](https://pan.baidu.com/s/1_b6XWs7LiHQfIAKVUOXqNg?pwd=2i9p) with the extracted features for tcga and C16 by CtransPath and ResNet18.
 (Note that these are relatively small bag lengths for C16, which excludes more background regions but may miss some foreground regions.)
