### ISSUE TITLE
您好！请问您所用的Resnet18的预训练权重是哪个版本的

### ISSUE THREAD

**Issue by Raymvp** [HHHedo/IBMIL#19]
我使用DSMIL的compute feature的代码，用imagenet 预训练的resnet18作为提取器，提取了patch特征。
之后用了您的代码复现各种模型，发现各个模型的效果要好于您论文中的结果。 我猜测是resnet18的预训练特征不同，您能提供resnet18的参数吗？或者您提取好的特征也可以。
或者pytorch的版本是否可能影响提取的特征？

**Comment by HHHedo** [comment]
Hi, 
We provide the details in the supplymentary "We adopt the ImageNet pretrained model officially released by PyTorch (https:
//download.pytorch.org/models/resnet18-5c106cde.pth)."
As far as I know, the main difference comes from the data splits. More recent papers tend to report the mean results of cross validations with different seeds, which I think is more reasonable.

**Comment by Raymvp** [comment]
我用的也是这个提取器权重。但是几个模型的效果都要好不少，即使在多次随机split。 您能分享特征文件给我吗

**Comment by HHHedo** [comment]
> 我用的也是这个提取器权重。但是几个模型的效果都要好不少，即使在多次随机split。 您能分享特征文件给我吗

This is the [Baidu cloud](https://pan.baidu.com/s/1_b6XWs7LiHQfIAKVUOXqNg?pwd=2i9p) with the extracted features for tcga and C16 by CtransPath and  ResNet18.
The tcga patches are processed by dsmil, and we pre-processe the WSIs ourselves and achieve around 7200 patches per WSI. (Note that these are relatively small bag lengths for C16, which excludes more background regions but may miss some foreground regions.)

For the performance, we believe this is related to many aspects like pre-processing, feature extraction and data splits. In your setting, you can also try interventional training and it is expected to further improve the performance.

**Comment by Raymvp** [comment]
感谢回复和分享特征。我们将在我们最新的工作中引用您卓越的文章。还有一个迷惑的点是，您论文中的结果报告的是最佳测试集的结果吗？   WSI其他多数工作都报告了最佳测试集的结果，对各种对比方法保持一致，也似乎是合理的。
我们观察到 一些模型在不同训练epoch的结果波动较大。

**Comment by HHHedo** [comment]
We report the results of the last epoch, see [issue.](https://github.com/HHHedo/IBMIL/issues/10#issuecomment-1875743426)
