### ISSUE TITLE
failed to reproduce the results under (ResNet-18, DSMIL, Camelyon16)

### ISSUE THREAD

**Issue by wuxchcandoit** [HHHedo/IBMIL#20]
Excuse me. May I ask you a simple question?
Is the classification task for dataset TCGA-NSCLC still a binary classification task even though TCGA-NSCLC includes two subtype?

**Comment by wuxchcandoit** [comment]
Besides, I failed to reproduce the results in the paper with the setting (ResNet-18 pretrained with ImageNet, DSMIL (without IBMIL), CAMELYON16) even though the public processed features in BaiduCloud (Camelyon16_ImageNet) have been used. I can only obtain about 73.xx AUC scores. What should I do to reproduce the results in the paper now? It that reasonable? Do you reproduce the same results as mine?

**Comment by HHHedo** [comment]
1. The num_class for tcga is set to 2. 

2. The unstable training of dsmil is also observed by myself (see [issue](https://github.com/binli123/dsmil-wsi/issues/59#issue-1403093315) ) and others (see [issue](https://github.com/HHHedo/IBMIL/issues/17#issue-2095929635)). One possible reason is that the attention-based aggregator failed to learn meaningful weight. You could observe these attention score during training and try different settings .

**Comment by wuxchcandoit** [comment]
Actually, I also failed to reproduce the results under the settings (ResNet-18 pretrained with ImageNet, TransMIL, Camelyon16). Therefore, the problem is not only about the unstable training of DSMIL.  Are the public pre-computed features in BaiduCloud reliable?

**Comment by HHHedo** [comment]
Since all the aggregators used in our paper are open-resourced, you may reproduce the baselines based on their repositories.
