### ISSUE TITLE
About Stage 1: Data pre-processing and computing features

### ISSUE THREAD

**Issue by JWZhao-uestc** [HHHedo/IBMIL#3]
Thanks for your awesome work. I want to confirm implementations about data pre-processing.

I think, I should replace the Resnet18 with CtransPath to train the embedder using SimCLR. And load the pre-trained CtransPath model before training embedder. After that, I should use the trained embedder as feature extractor.

Could you please tell me if my implementation is  correct? If not, could you please tell me what I should do correctly. 

Thank you!

**Comment by HHHedo** [comment]
If you want to train CtransPath using SimCLR, you can just leave it randomly initialized.
If you want to use the pre-trained CtransPath, you do not need to train the embedder but directly use it.

**Comment by JWZhao-uestc** [comment]
Thanks for your reply. I will try it again.
