### ISSUE TITLE
The parameter "background_t" in deepzoom_tiler.py

### ISSUE THREAD

**Issue by JWZhao-uestc** [HHHedo/IBMIL#5]
Hello,

Thanks for your awesome work again. Could you please tell me  the parameter "background_t" in file 'deepzoom_tiler.py' you used while tiling the raw WSI Images.

Looking forward to your reply, Thank you.

**Comment by HHHedo** [comment]
Hello,

I recommend using the data pre-processing in [dsmil](https://github.com/binli123/dsmil-wsi/).
However, as mentioned in our paper, we use the processed C16 in our previous work (which is mainly based on this [repo](https://github.com/deroneriksson/python-wsi-preprocessing)), and the released TCGA patches by [dsmil](https://github.com/binli123/dsmil-wsi/).

**Comment by JWZhao-uestc** [comment]
Thanks for your kind replay. I will try it as mentioned.
